language: ruby
sudo: required
warnings_are_errors: true
rvm:
  - 2.1
script: # let's just see if it installs and builds
  - pip install --user mkdocs
  - mkdocs build --clean
  # Ignoring this for now. - bundle exec htmlproofer ./site --only-4xx --file-ignore [""]
notifications:
  email:
    on_success: change
    on_failure: change