language: ruby
sudo: required
warnings_are_errors: true
rvm:
  - 2.1
script: # let's just see if it installs and builds
  - pip install --user mkdocs
  - mkdocs build --clean
notifications: #quiet for now
  email:
    on_success: never
    on_failure: never